name: conference_management
description: "A new Flutter project."

# Prevent package from being accidentally published to pub.dev
publish_to: 'none' # Remove this line if you want to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  # API calls management
  http: ^1.1.0
  json_serializable: ^6.5.1

  # HTTP client for network requests
  dio: ^5.2.0

  # State management
  provider: ^6.0.5
  riverpod: ^2.3.0

  # Security and storage management
  flutter_secure_storage: ^9.2.2
  shared_preferences: ^2.2.0

  # Form and validation handling
  flutter_form_builder: ^9.5.0
  intl: ^0.19.0

  # UI and advanced widgets
  flutter_slidable: ^3.1.1
  syncfusion_flutter_datagrid: ^27.2.2

  # Routing and navigation
  go_router: ^14.6.0

  # Lints for good coding practices
  flutter_lints: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  # Enable Material Design icons
  uses-material-design: true

  # Optional: Add assets section for images or other resources
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # Optional: Add custom fonts here
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

platforms:
  web: null # This enables Flutter Web
